### PR TITLE
"A week ago" in russian is "Неделю назад"

### PR DESCRIPTION
**Pull request by gronblack**
May be could you add these changes to the russian locale? 
In english locale it is "a week ago", and would like to have similar words for russian.

### CODE REVIEW

**Comment by catamphetamine** [comment]
published `javascript-time-ago@2.0.8`

**Comment by gronblack** [comment]
Thank you very match!

**Comment by catamphetamine** [comment]
@gronblack

maxresdefault

**Comment by gronblack** [comment]
:) Yea, my english is bed.

**Pull request merged**
